drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
drop table if exists audiorecord_t
drop table if exists book_t
drop table if exists category_t
drop table if exists category_title_r
drop table if exists item_t
drop table if exists title_t
